name: Add new HTTP result
description: Suggestion to add a new HTTP request
title: "[HTTP]: "
labels: ["HTTP"]
projects: ["projects/14"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the role of a request
    validations:
      required: true
  - type: markdown
    attributes:
      value: "---"
  - type: dropdown
    id: request_type
    attributes:
      label: Request type
      description: HTTP request type
      options:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "---"
  - type: textarea
    id: request_model
    attributes:
      label: Request model
      description: How the request should look like
      value: "none"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "---"
  - type: textarea
    id: response_positive
    attributes:
      label: Response positive
      description: What the server should return in case of a positive result
      value: "none"
    validations:
      required: true
  - type: input
    id: response_positive_status_code
    attributes:
      label: Response positive status code
      description: What status will the server return if the result is positive
      value: "200"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "---"
  - type: textarea
    id: response_negative
    attributes:
      label: Response negative
      description: What the server should return in case of a negative result
      value: "none"
    validations:
      required: true
  - type: input
    id: response_negative_status_code
    attributes:
      label: Response negative status code
      description: What status will the server return if the result is negative
      value: "200"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "---"
  - type: input
    id: permission
    attributes:
      label: Permission
      description: Is there any permission needed to execute this request
      render: :x: Unchecked
    validations:
      required: false
